### ISSUE TITLE
Error message on all actions when there are multiple items  in the project with SM

### ISSUE THREAD

**Issue by antonjazzsax** [carrus2049/reaper_SM_tweaker#10]
I've just opened onr of the projects I was working on, where items have lots of SMs, and here, when I try to use these actions I get the following error message:
"No stretch marker in first selected item at edit cursor"

It won't adjust SMs on subsequent items. 
if I go to the "first item" and place the SM there it will allow me to adjust it, but only in one direction, because after the action is executed, the edit cursor jumps back to the random position at the beginning of the time line

**Comment by carrus2049** [comment]
Currently the item to process is determined by item selection(highlight) state, which may be somehow problematic. Would you post a screenshot of the project arrangement view which reproduce these issues?

**Comment by antonjazzsax** [comment]
Hi.
I've uploaded a project for you, so you can recreate the issue yourself.
Sorry for the big size. It was actually one of the projects I was working on recently.
please follow this link;
(The link is still being processed so the project should be downloadable after an hour from the time this message is sent.)

https://mega.nz/folder/Dl9jyJYA#qRhR4MeQiYDc9Moqhh-17g

**Comment by carrus2049** [comment]
Thanks for uploading the whole thing.

This issue alongside with [issue](https://github.com/carrus2049/reaper_SM_tweaker/issues/7#issue-2318848153) is caused by:

1. media take play rate other than 1 (in your project it's ~0.9x) is not handled in the process of computing the project time of stretch marker
2. item position for those which is non 0 is not handled in.

Those are likely fixed  in version 0.0.4, play try them out and see if there's furthur issue!

**Comment by antonjazzsax** [comment]
Thank you very much! Looking forward to your update

**Comment by carrus2049** [comment]
> Thank you very much! Looking forward to your update

0.0.4 is already pushed on the main branch!

**Comment by antonjazzsax** [comment]
Thank you very much carrus2049! Tested now a little bit. Everything works rather nicely now. If I notice any other issues I'll post another note on it. But thank you so much
